import faker from "faker";

const Incidents = [
  {
    id: 1,
    createdOn: faker.date.past(),
    createdBy: 53,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 2,
    createdOn: faker.date.past(),
    createdBy: 20,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 3,
    createdOn: faker.date.past(),
    createdBy: 35,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 4,
    createdOn: faker.date.past(),
    createdBy: 4,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 5,
    createdOn: faker.date.past(),
    createdBy: 40,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 6,
    createdOn: faker.date.past(),
    createdBy: 11,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 7,
    createdOn: faker.date.past(),
    createdBy: 10,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: 8,
    createdOn: faker.date.past(),
    createdBy: 24,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
]

export default Incidents;