import faker from "faker";

const Incidents = [
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 2,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 3,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 4,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 5,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 6,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 7,
    type: "Red Flag",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 8,
    type: "intervention",
    location: `${faker.address.longitude()}, ${faker.address.latitude()}`,
    status: "draft",
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
]

export default Incidents;