import faker from "faker";

const Incidents = [
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: 'intervention',
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: "Red Flag",
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: 'intervention',
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: "Red Flag",
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: 'intervention',
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: 'intervention',
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: "Red Flag",
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
  {
    id: faker.random.number(),
    createdOn: faker.date.past(),
    createdBy: 1,
    type: 'intervention',
    location: faker.address.streetAddress() + faker.address.city(),
    status: draft,
    images:[],
    videos: [],
    comment: faker.lorem.sentences(),
  },
]

export default Incidents;